### ISSUE TITLE
Desyncs

### ISSUE THREAD

**Issue by proepkes** [mrdav30/LockstepRTSEngine#2] opened 2019-01-07 13:06 UTC
I've build the sample scene and connected two players over photon network with John's PhotonNetworkHelper
When the game starts, both players have the same state hash, but after player 1 selected a few units and moved around a bit, the state hash became different for the two players. In the long run the differences became more and more noticable.

**Comment by mrdav30** [comment] 2019-01-08 14:26
Hi proepkes, I've noticed the same issue while developing and plan on focusing this next.  I got ahead of myself with other features and refactoring that I wasn't keeping an eye on the hash state. I haven't tested over a simulated network yet, but running the hashed replay displays the same behavior (in-game replay commented out in /Assets/Core/Game/Managers/GameManager/RTSGameManager.cs) you described.

**Comment by Zelfire** [comment] 2019-06-26 10:39
Hello, is the development on this project still ongoing?  I think what is causing the desyns, it is in the physicsManager class.  I'm a complete amateur to programming but john pan inspired me to try make my own rts game with no prior knowledge of programming.  I hope you guys continue  in this endevour.  Anyway the desyns happen because when john introduced agents culling and added the function: 	

internal static int CullDistributor
		{
			get
			{
				if (_cullDistributor > 1)
					_cullDistributor = -1;
				return _cullDistributor++;
			}
		}
everytime the replay plays, the cullDistributor variable is either -1,0 or 1, which leads to desyns in 2/3 cases.  

So add a reset culldistributor function:
        static void  ResetCullDistributor()
        {
                _cullDistributor = 0;
        }

and call it here: 
		static void ResetVars()
		{
			for (int i = 0; i < PeakCount; i++)
			{
				SimObjects[i] = null;
			}
			DynamicSimObjects.FastClear();
			Raycaster._Version = 0;
			PeakCount = 0;
			CachedIDs.FastClear();

			CollisionPair.CurrentCollisionPair = null;
                        **PhysicsManager.ResetCullDistributor();**
			PeakCount = 0;
			AssimilatedCount = 0;

			Partition.Initialize();
			RanCollisionPairs.FastClear();
			InactiveCollisionPairs.FastClear();

			_positionCycler = 0;
		}

hope that helps as I haven't actually looked at your code but I assume it is the same issue as in SnpM

**Comment by mrdav30** [comment] 2019-06-26 16:43
Hi Zelfire, I've been extremely busy with everyday life, but yes, this project is still ongoing.  I hope to start development again soon within the coming weeks as I wrap other projects up.  As soon as I get the chance I'll try integrating this and see if it helps resolve the issue, or you can and submit the pull request.  Since I'm only one developer, I can use all the help I can get, so thank you for calling this out.

**Comment by Zelfire** [comment] 2019-06-27 10:18
Good to hear :).  I'm not very good with coding, still learning from just looking at the codes and trying to understand them, else I would help you with this. I work as a pharmacist and just try to do this as a little hobby on my days off. 

When i am able to make some abilities scripts I'll share them.

Massive thanks for your work on this project BTW! People like you and john inspire me and I'm sure many others.

**Comment by mrdav30** [comment] 2019-07-29 20:54
Hey guys,
The desync issues should be resolved with the latest commit to the dev branch.  Please test it out and let me know if you still encounter any more as well as what was occurring when it happened.  The majority of the desyncs I corrected were caused by not sending commands to the frame manager.  I resolved these by separating a lot of the ability decision making into the agent ai (aka lsinfluencer).

**Comment by mrdav30** [comment] 2019-09-19 00:24
Closing this for now, this issue with desyncs should be solved

**Closed as completed by mrdav30** 2019-09-19 00:24 UTC
Labels: bug
